/*
 *     Kingdoms Plugin
 *     Copyright (C) 2022  Fisher2911
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package io.github.fisher2911.kingdoms.message;

import io.github.fisher2911.kingdoms.util.EnumUtil;
import org.jetbrains.annotations.Nullable;

public enum Message {

    ALREADY_IN_KINGDOM,
    NO_PERMISSION_TO_CREATE_KINGDOM,
    CANNOT_AFFORD_TO_CREATE_KINGDOM,
    CANNOT_AFFORD_TO_UPGRADE,
    KINGDOM_ALREADY_EXISTS,
    CREATED_KINGDOM,
    INVALID_COMMAND_EXECUTOR,
    NO_COMMAND_PERMISSION,
    NOT_IN_KINGDOM,
    KINGDOM_NOT_FOUND,
    NO_KINGDOM_PERMISSION,
    CANNOT_EDIT_KINGDOM_PERMISSION,
    ALREADY_CLAIMED,
    SUCCESSFUL_CHUNK_CLAIM,
    SUCCESSFUL_CHUNK_UNCLAIM,
    NOT_CLAIMED_BY_KINGDOM,
    NO_ROLE_FOUND,
    ALREADY_INVITED,
    SENT_KINGDOM_INVITE_EXPIRED,
    RECEIVED_KINGDOM_INVITE_EXPIRED,
    NEW_MEMBER_JOINED_KINGDOM,
    JOINED_KINGDOM,
    OTHER_KINGDOM_FULL,
    ALREADY_MAX_UPGRADE_LEVEL,
    UPGRADE_DOES_NOT_EXIST,
    LEVEL_UP_UPGRADE_SUCCESSFUL,
    NO_AVAILABLE_CHUNKS,
    INVITED_MEMBER,
    RECEIVED_INVITE,
    NOT_INVITED_TO_KINGDOM,
    SUCCESSFUL_RELOAD,
    KINGDOM_INFO,
    KICKED_OTHER,
    KICKED_FROM_KINGDOM,
    NOT_IN_SAME_KINGDOM,
    SET_OTHER_ROLE,
    OWN_ROLE_SET,
    SENT_RELATION_REQUEST_EXPIRED,
    RECEIVED_RELATION_REQUEST_EXPIRED,
    ACCEPTED_RELATION_REQUEST,
    RELATION_REQUEST_ACCEPTED,
    SENT_RELATION_REQUEST,
    RECEIVED_RELATION_REQUEST,
    REMOVED_RELATION_TO,
    RELATION_REMOVED_FROM,
    CANNOT_RELATE_TO_SELF_KINGDOM,
    ENTERED_KINGDOM_LAND,
    LEFT_KINGDOM_LAND,
    ENTERED_WILDERNESS_LAND,
    LEADER_CANNOT_LEAVE_KINGDOM,
    MEMBER_LEFT_KINGDOM,
    YOU_LEFT_KINGDOM,
    CONFIRM_DISBAND_KINGDOM,
    DISBAND_KINGDOM_CONFIRMATION_EXPIRED,
    KINGDOM_DISBANDED,
    MUST_BE_IN_KINGDOM_TO_CHANGE_CHAT,
    CHAT_CHANNEL_CHANGED,
    CHAT_CHANNEL_NOT_FOUND,
    KINGDOM_BANK_WITHDRAW_SUCCESS,
    KINGDOM_BANK_DEPOSIT_SUCCESS,
    NOT_ENOUGH_FUNDS,
    KINGDOM_BANK_NOT_LARGE_ENOUGH,
    USER_NOT_ENOUGH_MONEY,
    KINGDOM_BALANCE,
    MAX_RELATIONS_REACHED,
    SET_KINGDOM_HOME,
    TELEPORT_SUCCESS,
    TELEPORT_CANCELLED_MOVEMENT,
    TELEPORT_CANCELLED,
    TELEPORT_COUNTDOWN,
    KINGDOM_LOCATION_NOT_SET,
    USER_DATA_LOAD_ERROR,
    INVALID_POSITION,
    ENABLED_AUTO_CLAIM,
    ENABLED_AUTO_UNCLAIM,
    DISABLED_AUTO_CLAIM,
    DISABLED_AUTO_UNCLAIM,
    PLAYER_NOT_FOUND,
    CANNOT_SET_PERMISSION_ROLE,
    ROLE_DOES_NOT_EXIST,
    CANNOT_SET_SELF_ROLE,
    KINGDOM_DESCRIPTION,
    INVALID_KINGDOM_NAME_LENGTH,
    INVALID_KINGDOM_DESCRIPTION_LENGTH,
    CHANGED_KINGDOM_DESCRIPTION,
    CHANGED_KINGDOM_NAME,
    KINGDOM_NAME_INFO,
    COMMAND_HELP_FORMAT,
    COMMAND_HELP_HEADER,
    COMMAND_HELP_FOOTER,
    ADMIN_COMMAND_HELP_FORMAT,
    ADMIN_COMMAND_HELP_HEADER,
    ADMIN_COMMAND_HELP_FOOTER,
    CANNOT_INVITE_SELF,
    CANNOT_CLAIM_HERE,

    ;

    public String getConfigPath() {
        return this.toString().toLowerCase().replace("_", "-");
    }

    @Nullable
    public static Message fromConfigPath(String path) {
        return EnumUtil.valueOf(Message.class, path.toUpperCase().replace("-", "_"));
    }

}
