name: Kingdoms
version: '${version}'
main: io.github.fisher2911.kingdoms.Kingdoms
api-version: 1.16
authors: [ Fisher2911 ]
depend: [ Vault ]
softdepend: [ WorldGuard ]
commands:
  kingdom:
    description: test
    aliases: ["k"]
